[workspace]
name = "sentence-diagramm"
channels = ["conda-forge"]
platforms = ["osx-arm64", "win-64"]

[dependencies]
python = ">=3.12,<3.13"
streamlit = "*"
spacy = "*"
pandas = "*"
pip = "*"

[tasks]
app = "streamlit run app.py"
cli = "python cli.py"
test = "pytest tests/ -q"
download-models = "python -m spacy download en_core_web_sm && python -m spacy download de_core_news_sm"

[pypi-dependencies]
pytest = ">=9.1.1, <10"
en-core-web-sm = { url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl" }
de-core-news-sm = { url = "https://github.com/explosion/spacy-models/releases/download/de_core_news_sm-3.8.0/de_core_news_sm-3.8.0-py3-none-any.whl" }
deep-translator = ">=1.11.4, <2"
